@id =24cf2aac-d33c-488a-8f43-3075f3a2f5c5
PUT http://localhost:5143/Breakfasts/({{id}})
Content-Type: application/json

{
    "name": "Firwanaa Sheridan",
    "description": "Vegan everything! Join us for a healthy breakfast..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}